"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['./behringerbridge.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True,
 'report_missing_from_imports': True,
 'site_packages': True,
  'packages': ['rumps' ],
   'plist': {
        'LSUIElement': True,
    },
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app', 'python-rtmidi' ],
)
